#!/bin/bash

# This script is meant to be run from inside the Sonobuoy pod
bin/run-all

cp -r ./reports /tmp/results

tar czvf /tmp/results/results.tar.gz -C /tmp/results .

echo -n /tmp/results/results.tar.gz > /tmp/results/done
